spring:
  datasource:
    username: heartcare_db_user
    password: AxVwb8E5UEm2I93eSs0UYsviYC1cXxk8
    url: jdbc:postgresql://dpg-cov0f2o21fec73bvtuo0-a.oregon-postgres.render.com:5432/heartcare_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "creusa.rosario88@gmail.com"
    password: "wsuehfrenpjfbejf"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

base:
  url: "http://localhost:8080"
